remote_theme: orderedlist/orderedlist
plugins:
  - jekyll-remote-theme

title: Eleonora Minaeva
author: Eleonora Minaeva
position: PhD Researcher in Political Science
affiliation: European University Institute

email: eleonora.minaeva@eui.eu

avatar: /assets/images/eminaeva-pic.jpg

social:
  cv: CV-2025.pdf
  github: https://github.com/eminaeva
  scholar: https://scholar.google.com/citations?user=m_UTmvAAAAAJ&hl=en
  linkedin: https://www.linkedin.com/in/eleonora-minaeva-b84929125/
